### ISSUE TITLE
Unable to connect to a host which has "crate" in the dns name

### ISSUE THREAD

**Issue by tellezb** [crate/crate-jdbc#198]
This seems to happen with Crate's jdbc driver 2.0+.

Connection fails when attempting to connect to "crate://**crate**-909550290.us-west-2.elb.amazonaws.com:5432". The Crate jdbc driver is changing my connection to "postgresql://**postgresql**-909550290.us-west-2.elb.amazonaws.com:5432" before attempting to open the connection.

I'm guessing this line in CrateDriver.java is the source of the issue:

`url = url.replace(CRATE_PROTOCOL, PSQL_PROTOCOL);`

My short-term workaround is to avoid the term "crate" in my load balancer's DNS name. But this should be fixed.

**Comment by chaudum** [comment]
hi @tellezb 
thanks for reporting! the fix #199 is already merged and will be available with the next release.

**Comment by chaudum** [comment]
@tellezb `crate-jdbc 2.1.3` has been released today https://github.com/crate/crate-jdbc/blob/master/CHANGES.txt#L8-L14
