### ISSUE TITLE
Squirrel Error: Statement: getMoreResults not supported

### ISSUE THREAD

**Issue by joalmjoalm** [crate/crate-jdbc#201]
Hi 

I just launched Crate ver 1.0.2 and accessed it with Squirrel using the standalone jdbc driver 2.1.3 with squirrel-config set to classname 'io.crate.client.jdbc.CrateDriver' and url to 'crate://ipadress:5432/'

Added a few tables and they appeared in Crate gui.

But I cant get any results back in Squirrel from sql statements. It says 
Error: Statement: getMoreResults not supported
SQLState:  null
ErrorCode: 0

Can it be fixed as a workaround by properties/params in Squirrel or is waiting for a fix in the driver needed ?

I didnt have this problem with Crate 55.6 and jdbc 1.13.1. I get it to work with driver jdbc.postgresql.org but I guess that driver holds standard features not having Crate specific features, or?

I'm also not able to connect to same Crate version from Streamsets described at 
https://crate.io/docs/tools/streamsets/ but using standalone crate-jdbc driver 2.1.3 and connect on port 5432. Dont know if this is the same cause, pls verify. 

Regards

Jonas

**Comment by joemoe** [comment]
@joalmjoalm thanks for reporting. we are aware of this problem it is the same like #193.

**Comment by chaudum** [comment]
@joalmjoalm we fixed the issue and it will be available with the next release.

**Comment by joalmjoalm** [comment]
thank you very much, appreciate your work
