### ISSUE TITLE
 JDBC_06 - Failed to initialize connection from Streamsets

### ISSUE THREAD

**Issue by joalmjoalm** [crate/crate-jdbc#205]
Hi

Squirrel works fine with Crate 1.0.2 and jdbc standalone driver 2.1.4. 

But I dont get Streamsets to work with Crate 1.0.2 with the standalone driver 2.1.4. I have tested w Streamsets 2.2.1.0 and 1.6.0.0.

Any special config /jdbc properties I'm missing or any fix needed in the jdbc 2.1.4 ?

get error: JDBC_00 - Cannot connect to specified database: com.streamsets.pipeline.api.StageException: JDBC_06 - Failed to initialize connection pool: io.crate.shade.org.postgresql.util.PSQLException: ERROR: SQLParseException: line 1:13: no viable alternative at input 'CHARACTERISTICS'

Dont know if this is the same as #193 .

Jonas

**Comment by joalmjoalm** [comment]
I unchecked the box "Enforce Read-only Connection" in Streamsets and it works like a charm. Case closed.

**Comment by techtutorials** [comment]
See this Solution complete steps to follow

https://arkit.co.in/streamsets-jdbc-connection-mssql/
