### ISSUE TITLE
ERROR: JOIN with sub queries is not supported [SQL State=XX000]

### ISSUE THREAD

**Issue by sansom** [crate/crate-jdbc#213]
I would like to count a table of trading volume, because the member of the basic information is in another table, so the need to joins,but can not get the results in a SQL, am I wrong? what hapend with this:

SELECT a.member_id,,b.name,count(*)
FROM test_01.order  a
left  join test_02.member b on a.member_id=b.member_id
group by a.member_id

ERROR: JOIN with sub queries is not supported [SQL State=XX000]
ERROR: GROUP BY on JOINS is not supported [SQL State=XX000]

JDBC version:2.1.6

**Comment by mfussenegger** [comment]
As the error message indicates, group by on joins are currently not supported. See https://github.com/crate/crate/issues/4672
