### ISSUE TITLE
No updated row count when query begins with new line.

### ISSUE THREAD

**Issue by s4s0l** [crate/crate-jdbc#236]
Don't know if its jdbc bug or crate itself but when doing:
```
val ss = session.connection.prepareStatement(
            s"""
               update locks.locks set when_overdue = ?, by_who =?, by_who_id=?  where NAME = ? and "_version"=?""")        
// .. skipped
val updated1 = ss.executeUpdate()
```
updated1 is 0

but when 
```
val ss = session.connection.prepareStatement(
            s"""update locks.locks set when_overdue = ?, by_who =?, by_who_id=?  where NAME = ? and "_version"=?""")
```
updated1 is 1, as expected. The difference is new line at the beginning of statement. What i've found out is that io.crate.shade.org.postgresql.core.v3.QueryExecutorImpl.interpretCommandStatus gets status in form "\n 1" in first case and "UPDATE 1" in second.

Seems like a small problem but I lost whole day to figure it out:)

CradeJdbc version 2.2.0, crate database version = 2.1.5

**Comment by mxm** [comment]
Hi @s4s0l! Thanks for reporting the issue and for your investigation so far! CrateDB wasn't responding correctly to the JDBC protocol when the query contained whitespace. Pull request is out: https://github.com/crate/crate/pull/6203

**Comment by mxm** [comment]
Release will be out later today.
