### ISSUE TITLE
When a crate node machine shutdow and application restarted, using crate-jdbc will cause the thread to be busy

### ISSUE THREAD

**Issue by ghsau** [crate/crate-jdbc#238]
The last time our application in the restart when there is a lot of thread busy, because our crate cluster in a node machine is shutdown, most of the threads are blocked to the following code:
              
NettyTransport.java
```
protected NettyTransport.NodeChannels connectToChannelsLight(DiscoveryNode node) {
	 InetSocketAddress address = ((InetSocketTransportAddress)node.address()).address();
	 ChannelFuture connect = this.clientBootstrap.connect(address);
	 connect.awaitUninterruptibly((long)((double)this.connectTimeout.millis() * 1.5D));///////////////////////////////////////////////////////////////////////////////// blocked here
	 if(!connect.isSuccess()) {
			throw new ConnectTransportException(node, "connect_timeout[" + this.connectTimeout + "]", connect.getCause());
	 } else {
			Channel[] channels = new Channel[]{connect.getChannel()};
			channels[0].getCloseFuture().addListener(new NettyTransport.ChannelCloseListener(node, null));
			return new NettyTransport.NodeChannels(channels, channels, channels, channels, channels);
	 }
}
```
       
You can see here that there is a timeout parameter “this.connectTimeout”, the default value for this parameter is 30 seconds, but I can not change this parameter through crate-jdbc.
       
### Environment
- datasource     tomcat-jdbc(8.0.20)
- crate-jdbc      1.10.0
- crate-client    0.54.0
- crate-server   0.54.0(7 nodes)
       You must shutdown the crate node machine(connection timeout) instead of killing the crate process(connection refused).

### Problem analysis
When the application is running, then shutdown a crate node machine, and this will not happen, because jdbc connection has been established. When the application restart, if there is a query request, jdbc connection needs to be initialized, and its internal connection with all crate nodes, if a node network barrier, it will block. If qps is large, the thread pool is quickly filled because the default blocking time is long and no connection is available.

Looking forward for your reply, thank you!

**Comment by jodok** [comment]
hi @ghsau, we've switched to the postgres wire protocol to connect via JDBC and no longer support the netty-based crate-client and the jdbc driver <2.x.
is it possible for you to upgrade to a recent version and use that jdbc driver? (make sure to follow the upgrade instructions as 0.54 is rather old and will need index migration)...

**Comment by ghsau** [comment]
Is there a problem with the new version?

**Comment by jodok** [comment]
not that we know of :)

**Comment by ghsau** [comment]
Let me try, thx!
