### ISSUE TITLE
unmappable character (0x90) for encoding windows-1252

### ISSUE THREAD

**Issue by trevrobwhite** [crate/crate-jdbc#272]
Hi Crate Team,
It seems the JAR file will not build under Windows 10, I've managed to throw this over to a Linux box to perform the build but thought I'd let you know.

I tried the standard and standalone jar.
C:\Temp\crate-jdbc>gradlew.bat standaloneJar

> Task :pg:preprocessJava
Preproces: upstream/pgjdbc/src/main/java -> C:\Temp\crate-jdbc\pg\build/jcp/main/java
Preproces: upstream/pgjdbc/src/main/resources -> C:\Temp\crate-jdbc\pg\build/jcp/main/resources

> Task :pg:compileJava
C:\Temp\crate-jdbc\pg\build\jcp\main\java\org\postgresql\core\EncodingPredictor.java:43: error: unmappable character (0x90) for encoding windows-1252
          new Translation("ðÆð?ðûð?ð×", null, "ru", "WIN", "ALT", "KOI8"),
                              ^
C:\Temp\crate-jdbc\pg\build\jcp\main\java\org\postgresql\core\EncodingPredictor.java:43: error: unmappable character (0x9D) for encoding windows-1252
          new Translation("ðÆð?ðûð?ð×", null, "ru", "WIN", "ALT", "KOI8"),
                                  ^
C:\Temp\crate-jdbc\pg\build\jcp\main\java\org\postgresql\core\EncodingPredictor.java:47: error: unmappable character (0x81) for encoding windows-1252
          new Translation("FATAL", new String[]{"Ò?»Õ¡ÿÕ£¿Ò?ùÒ?¥Ò?øÒéô" /* ~ does not exist */,
                                                  ^
C:\Temp\crate-jdbc\pg\build\jcp\main\java\org\postgresql\core\EncodingPredictor.java:47: error: unmappable character (0x81) for encoding windows-1252
          new Translation("FATAL", new String[]{"Ò?»Õ¡ÿÕ£¿Ò?ùÒ?¥Ò?øÒéô" /* ~ does not exist */,
                                                           ^
C:\Temp\crate-jdbc\pg\build\jcp\main\java\org\postgresql\core\EncodingPredictor.java:47: error: unmappable character (0x81) for encoding windows-1252
          new Translation("FATAL", new String[]{"Ò?»Õ¡ÿÕ£¿Ò?ùÒ?¥Ò?øÒéô" /* ~ does not exist */,
                                                              ^
C:\Temp\crate-jdbc\pg\build\jcp\main\java\org\postgresql\core\EncodingPredictor.java:47: error: unmappable character (0x81) for encoding windows-1252
          new Translation("FATAL", new String[]{"Ò?»Õ¡ÿÕ£¿Ò?ùÒ?¥Ò?øÒéô" /* ~ does not exist */,
                                                                 ^
6 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':pg:compileJava'.
> Compilation failed with exit code 1; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
2 actionable tasks: 2 executed

C:\Temp\crate-jdbc>

**Comment by chaudum** [comment]
hi @trevrobwhite 
Thanks for the heads up. The Crate JDBC driver is based on pgjdbc which requires and UTF-8 environment to build. You need to make sure that your system locale are set correctly to `xxx.UTF-8`, see https://docs.microsoft.com/en-us/powershell/module/international/set-winsystemlocale?view=win10-ps

(Your error will also happen if you had set the locale wrong on Linux.)

**Comment by trevrobwhite** [comment]
Many thanks @chaudum, could you include that in your README.rst for installation, that would be really helpful for others.

Thanks again.

**Comment by chaudum** [comment]
If you need the jar file (both slim and standalone), you can download it from bintray https://bintray.com/crate/crate/crate-jdbc it's not required to build it from source :)
Also will add it to the readme.

**Comment by trevrobwhite** [comment]
@chaudum excellent many thanks.

**Comment by trevrobwhite** [comment]
@chaudum I'm probably being stupid so apologies but on bintray it's saying "No direct downloads selected for this package" for all the versions I tried.

**Comment by trevrobwhite** [comment]
Don't worry was me being stupid as thought was looking under general not files, sorry.
