### ISSUE TITLE
Deadlock in PgStatement.killTimerTask on crate-jdbc 2.5.1

### ISSUE THREAD

**Issue by echarlus** [crate/crate-jdbc#299]
@seut I got the deadlock again today (see first issue #296), even though I've upgraded to 2.5.1 (using crate-jdbc-standalone-2.5.1.jar)
Here's the log :
"http-nio-8080-exec-3" #23 daemon prio=5 os_prio=0 tid=0x00007fc4ec506800 nid=0x4b7d in Object.wait() [0x00007fc49fdfb000] java.lang.Thread.State: TIMED_WAITING (on object monitor) at java.lang.Object.wait(Native Method) at io.crate.shade.org.postgresql.jdbc.PgStatement.killTimerTask(PgStatement.java:984) - locked <0x00000000cc2263d8> (a io.crate.shade.org.postgresql.jdbc.PgConnection) at io.crate.shade.org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:445) at io.crate.shade.org.postgresql.jdbc.PgStatement.execute(PgStatement.java:366) at io.crate.shade.org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:145) at io.crate.shade.org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:122) at io.crate.shade.org.postgresql.jdbc.PgConnection.isValid(PgConnection.java:1412) at fr.ocell.ovisuserver.model.DB.getConnection(DB.java:22) 
This happens when a web requests hits tomcat which spawns a new thread to handle the request. I thy to get a hold of the underlying DB connection and I get stuck (I have a lock to prevent multiple threads opening a connection at the same time). The thread trying to get the DB is suck on the isValid() method of the connection ...

**Comment by echarlus** [comment]
Any update on this ? I'm still getting the issue from time to time ...

**Comment by seut** [comment]
@echarlus Could you please share the properties your are passing in either via connection URL or `connect(...)` parameter?

**Comment by echarlus** [comment]
Hi @seut thanks for getting back to me. 
I'm using a simple connection URL : 
DriverManager.getConnection("jdbc:crate://localhost:5432/", null, null);

Issue arises from time to time, without any obvious pattern ...

**Comment by seut** [comment]
@echarlus Thanks for the information, could you also tell me what timeout value you are passing to `isValid(...)` please?

**Comment by echarlus** [comment]
I call this method from several places. I used to use 0 as value and I've started migrating to using 1 instead since I encountered the issue. I've not migrated everywhere yet ...

**Comment by seut** [comment]
Are you sharing a `Connection` or a `Statement` instance across multiple threads?

**Comment by echarlus** [comment]
yes I do share both across multiple threads

**Comment by seut** [comment]
Ok that is the issue as this is not supported by the pgjdbc implementation, also noted here https://jdbc.postgresql.org/documentation/head/statement.html. Only connections are safe to be used across multiple threads.

**Comment by echarlus** [comment]
Ok thanks for pointing this out. I'll review the code and make sure I do not share PreparedStatements across threads...

**Comment by seut** [comment]
👍  Ftr: I guess that one thread is calling `isValid()` while another one is concurrently calling `cancel()` which will then block each other.

**Comment by echarlus** [comment]
I never use cance() il my code, could this be called by the underlying layers ?

**Comment by omardawod119** [comment]
Hi @seut,

Is there any chance that this issue will be fixed? I have to admit that a big part of our application is legacy, and there is a lot of Connection and Statement sharing between Threads. 
Our application is today compatible with Oracle and SQL Anywhere. Trying to make it compatible with Postgres, but this issue is popping up all the time.
