### ISSUE TITLE
URLCoder error when using driver with streamsets

### ISSUE THREAD

**Issue by diegonc** [crate/crate-jdbc#302]
I'm using crate-jdbc as the driver of a JDBC Producer in StreamSets and I cannot get past the following error:

```
JDBC_00 - Cannot connect to specified database: com.zaxxer.hikari.pool.PoolInitializationException:
Exception during pool initialization: Could not initialize class io.crate.shade.org.postgresql.util.URLCoder
```

the JDBC url looks like this: `crate://192.168.2.4:4300/doc`.

Any idea why the URLCoder class could be failing to load?

Thanks

**Comment by seut** [comment]
This looks strange, I have no real clue how the static `UrlCoder` class can run into initialization errors (Nothing error-prone is done on the static initialization).

The only thing I see is that you maybe using the wrong port, `4300` by default is used by the inter-node communication (transport port). The default PGSQL/JDBC port is: `5432`.

**Comment by diegonc** [comment]
Ok, 5432 makes sense, indeed. This[1] guide I was following said 4300 though, so I wasn't sure what port to use.

However, I'm running another Postgre server in the same machine. Crate seems to be picking 5433 for its psql service instead.

BTW, the streamsets pipeline is meant to load records from that Postgre server into Crate. I first suspected a JAR version conflict between the two JDBC drivers could be causing the problem. But the crate driver contains a shaded pg driver, so I guess it shouldn't cause trouble.

[1] https://crate.io/docs/crate/guide/en/latest/tools/streamsets.html

**Comment by seut** [comment]
Ok so this issue is now solved by using the right port?
We will update our Streamsets guide asap, thanks for pointing this out!
If there is still an issue, feel free to re-open this.
