### ISSUE TITLE
Maven repository example does not work

### ISSUE THREAD

**Issue by kamejosh** [crate/crate-jdbc#333]
###  Documentation feedback

 
- Page title: Getting started
- Page URL: https://crate.io/docs/jdbc/en/latest/getting-started.html
- Source: https://github.com/crate/crate-jdbc/blob/master/docs/getting-started.rst

---

When using this Getting started guide to setup a Maven Project with CrateDB I got an error that some libraries could not be found (`JsonProcessingException`). The reason is that the repository in the example ha the ID `central` and is therefor overwriting the default maven repositories called `central`. Changing the name to e.g. `crate` would make using the current example a valid option. But I'm not usually a Java/Maven dev and don't know what the usual approach would be. But I think having an example code in the documentation should work without letting the user figure some problems out themselves.

**Comment by mechanomi** [comment]
thanks for reporting this, @kamejosh! I have asked one of our core engineers to review your suggestion and will happily fix once I hear back

**Comment by mechanomi** [comment]
update: @kovrus gives this a thumbs up! :)

**Comment by norosa** [comment]
this was fixed but never closed
