### ISSUE TITLE
Exception while updating a column with array of objects with nested objects

### ISSUE THREAD

**Issue by echarlus** [crate/crate-jdbc#336]
I'm struggling to update a column defined as : my_column ARRAY(OBJECT (DYNAMIC) ), I'm getting the following exception : 
`ERROR: [Ljava.lang.Object; cannot be cast to java.util.Map
	at io.crate.shade.org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at io.crate.shade.org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at io.crate.shade.org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at io.crate.shade.org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:442)
	at io.crate.shade.org.postgresql.jdbc.PgStatement.execute(PgStatement.java:366)
	at io.crate.shade.org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:145)
	at io.crate.shade.org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:122)
	at JdbcTest.main(JdbcTest.java:28)`

The following code sample shows this issue with crate-jdbc-standalone-2.5.1 on Crate 2.3.11

Create the following table & insert a row
`CREATE TABLE t1 (properties ARRAY(OBJECT (DYNAMIC)), id INTEGER);
insert into t1 (properties, id) values ([{"arr1"=[{"type"='test',"id"=1},{"val"=0.0025,"id"=2,"type"='test2'}],"type"=7}], 1);
`
Then try to update the row : 

```
import java.sql.*;
import java.util.HashMap;
import java.util.Map;

public class JdbcTest {
    public static void main(String[] args) {

        // CREATE TABLE t1 (properties ARRAY(OBJECT (DYNAMIC)), id INTEGER);
        // insert into t1 (properties, id) values ([{"arr1"=[{"type"='test',"id"=1},{"val"=0.0025,"id"=2,"type"='test2'}],"type"=7}], 1);

        try (Connection conn = DriverManager.getConnection("crate://localhost:5432/doc")) {
            System.out.println("INSERT");
            PreparedStatement updateStatement = conn.prepareStatement("update t1 set properties=? where id=?");
            updateStatement.setArray(1, conn.createArrayOf("object", new Map[]{
                    new HashMap<String, Object>() {{
                        put("col_int", 2);
                        put("col_str", "some other text");
                    }},
                    new HashMap<String, Object>() {{
                        put("col_int", 3);
                        put("col_str", "another text");
                        put("col_map", new HashMap<String, Object>() {{
                            put("test_obj", "value obj");
                        }});
                    }}
            }));
            updateStatement.setInt(2, 1);
            updateStatement.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
```

I've traced down the query and I'm also attaching a pcap  dump of the TCP Postgresql data
[update_column.pcapng.zip](https://github.com/crate/crate-jdbc/files/5903709/update_column.pcapng.zip)

It show that the data sent to the server is : 
{"{\"col_int\":2,\"col_str\":\"some other text\"}","{\"col_int\":3,\"col_str\":\"another text\",\"col_map\":{\"test_obj\":\"value obj\"}}"}

I had found an issue related to columns with array of objects  in the [crate project](https://github.com/crate/crate/issues/5620) but it's flagged as closed.

Any hints on why it's failing ? 
Thanks

**Comment by amotl** [comment]
Hi @echarlus,

thank you for the excellent report and apologies for the late reply. We will try to look into that soon.

With kind regards,
Andreas.

**Comment by mfussenegger** [comment]
Looks like this could be a bug within Crate 2.3.11

Any chance that you could upgrade to a recent version? I tested this with CrateDB 4.4 and there it works.

**Comment by mfussenegger** [comment]
Closing this because of lack of feedback. If this is still an issue please let us know.
