### ISSUE TITLE
Outdated documentation variants/versions still in Google index

### ISSUE THREAD

**Issue by amotl** [crate/crate-jdbc#343]
Hi there,

originally, @msbt found #342 on https://crate.io/docs/jdbc/en/2.0/.

It looks like some of the outdated versions are still indexed by Google, see https://eu.startpage.com/do/dsearch?query=cratedb+jdbc. Maybe we should add appropriate redirects?

With kind regards,
Andreas.

**Comment by norosa** [comment]
bounced it over to you. feel free to bounce it back

**Comment by amotl** [comment]
> one potential lead: do you have access to the google webmaster console? it has tools that let you inspect the robots directives and sitemaps it is aware of for your site. seems like a good place to start.

Can you have a look at this, @msbt or @proddata?

**Comment by msbt** [comment]
@norosa @amotl "Crawlers don't check for robots.txt files in subdirectories." Our goal back then was to remove the RTD links from the google index, which worked fine because there the robots.txt resides in root, but not if it's being routed through the reverse proxy.

The search console says "Indexed, not submitted in sitemap", so as long as the page is available publicly, it will stay there I reckon.

**Comment by amotl** [comment]
> Adding redirects for these old versions _would_ work, but it doesn't solve the underlying issue (why are these versions still in google?) [@norosa]

> The search console says "Indexed, not submitted in sitemap", so as long as the page is available publicly, it will stay there I reckon. [@msbt]

Wouldn't adding appropriate redirects be a valid option then?

**Comment by msbt** [comment]
>  @msbt: Is it possible to delete specific pages from the index within google webmaster console?

Sure, we can request url-removal for outdated content, but don't we want multiple versions available for older releases?

**Comment by amotl** [comment]
I believe it will be fine to have them _available_, right? I would vote for removing them from the Google index because I believe it will be sufficient to let users always be guided to the most recent version of the documentation when searching on Google?

**Comment by norosa** [comment]
no objections. in fact, anything not currently included in the active versions dropdown should be perged. from the RTD servers and google if possible. that stuff should be _gone_ gone. we have rewrites in place to send visitors to the correct and more up-to-date versions

**Comment by amotl** [comment]
> no objections

Fine. Let's proceed then and delete the outdated versions from anything which we can attach to?
