### ISSUE TITLE
Async JDBC Client

### ISSUE THREAD

**Issue by erenerdemli** [crate/crate-jdbc#355]
Do you have any plans on creating Async JDBC Driver,

Hence using crate in microservices platform such as Vertx, will be great addition

@see 
https://github.com/eclipse-vertx/vertx-sql-client

**Comment by mfussenegger** [comment]
Currently there are no plans to create a new async JDBC driver.

Instead we focus on improving the PostgreSQL compatiblity in CrateDB to make existing drivers work. Did you try the PostgreSQL vertx-sql-client to see if it already works with CrateDB?

**Comment by erenerdemli** [comment]
Yes it seems to work, thanks
