### ISSUE TITLE
Add test case for ...

### ISSUE THREAD

**Issue by amotl** [crate/crate-jdbc#380]
Maybe it makes sense to add a test case for GH-378 / GH-379, corresponding to https://github.com/crate/pgjdbc/pull/38?

> Changed ``getPrimaryKeys()`` SQL stmt to use the table schema as the schema instead of the table catalog. This fixes compatibility with CrateDB >= 5.1.0 as all catalog fields at the ``information_schema.tables`` schema expose now the correct catalog value (``crate``) instead of the table schema.

/cc @seut

**Comment by seut** [comment]
@amotl Thanks for mentioning.
This is already covered by `MetaDataITest.testGetPrimaryKeysPk()` which fails without the corresponding patches on CrateDB >= 5.1.0. I've just now verified this.
