### ISSUE TITLE
crate-jdbc 2.7 has many vulnerabilities.

### ISSUE THREAD

**Issue by alija83** [crate/crate-jdbc#386]
When accessing https://mvnrepository.com/artifact/io.crate/crate-jdbc/2.7.0 many vulnerabilities are identified by the site.

When scrolling down, all of those vulnerabilities are tied to jackson-databind (version 2.5.3) which is used by crate-jdbc (I did not verify if this is correct).

But when exploring the jackson-databind dependency, there is a newer version which does not have any vulnerabilities: 2.15.1

**Comment by amotl** [comment]
Dear @alija83,

thank you for your suggestion. I've submitted a corresponding patch at https://github.com/crate/pgjdbc/pull/44.

With kind regards,
Andreas.
