### ISSUE TITLE
Dependency on Log4j is not represented in build

### ISSUE THREAD

**Issue by rehevkor5** [crate/crate-jdbc#58]
The LoggingHelper class has a compile dependency on Log4j which is not expressed in the POM files.

In addition, the usage of Log4j classes such as ConsoleAppender makes it difficult to use log4j-over-slf4j  http://www.slf4j.org/legacy.html#log4j-over-slf4j It would be great if LoggingHelper would leave the logging configuration to the user, reducing the surface area of the Log4j dependency and enabling use of slf4j.

**Comment by mfelsche** [comment]
The whole LoggingHelper will be removed very very soon.
Thanks for reporting, we'll keep you updated on this.

**Comment by mfelsche** [comment]
the logginghelper stuff has been removed in commit 
ba8dbae1b00d2c875225bd8307f06faf1047f248 which is already released.
