### ISSUE TITLE
CratePreparedStatement.execute() returns null

### ISSUE THREAD

**Issue by wallner** [crate/crate-jdbc#69]
If a sql query does not provide a result ie. does not find any entries matching the query `CratePreparedStatement.execute()` returns `null` and not an empty `ResultSet` as would be expected. This breaks the contract of the [PreparedQuery interface](https://docs.oracle.com/javase/7/docs/api/java/sql/PreparedStatement.html#executeQuery()) and prevents [JDBI](http://jdbi.org/) to work.

A test to reproduce the this bug would be the following:
```java
public class executeQueryTest {


    private Connection connection;

    @Before
    public void setUpDatabase() throws ClassNotFoundException, SQLException {
        Class.forName("io.crate.client.jdbc.CrateDriver");
        connection = DriverManager.getConnection("crate://localhost:4300");
        connection.setAutoCommit(true);
    }

    @Test
    public void resultsetShouldBeEmpty() throws SQLException {
        String statement = "Select * from test where valueA = ?";
        PreparedStatement preparedStatement = connection.prepareStatement(statement);
        preparedStatement.setString(1, "itrrelevant");
        ResultSet result = preparedStatement.executeQuery();
        assertThat(result, notNullValue());
    }
}
```

**Comment by chaudum** [comment]
hi @wallner 

thanks for reporting. we'll take a look and come up with a fix :)
I'll let you know when it it available.

**Comment by wallner** [comment]
The fix for this bug is pretty trivial. I'm currently in the process of writing a few tests for it and will come up with a PR later today or tomorrow.

**Comment by chaudum** [comment]
cool, thanks!

**Comment by chaudum** [comment]
crate-jdbc 1.7.0 is released

https://bintray.com/crate/crate/crate-jdbc/1.7.0/view
https://github.com/crate/crate-jdbc/blob/master/CHANGES.txt#L5

**Comment by wallner** [comment]
Awesome! Thank you!
