### ISSUE TITLE
connectTimeout and socketTimeout are not configurable via the jdbc connection string

### ISSUE THREAD

**Issue by reversefold** [crate/crate-jdbc#81]
We are setting the connectTimeout and socketTimeout values for our mysql data source via query parameters on the connection string as such:
```
mysql://1.2.3.4/db?connectTimeout=10&socketTimeout=300
```
If we add this to a crate jdbc connection string these values get parsed as part of the port on the last node.

**Comment by celaus** [comment]
Hi, thanks for bringing this to our attention - this should not happen and we will take care of it. I'll update once it's done!

Thanks and all the best, Claus

**Comment by celaus** [comment]
Hi, we have fixed this issue and added the ability to configure timeouts via URL parameters to our backlog. The fix will be in the new release.

Cheers, Claus

**Comment by reversefold** [comment]
Ok, so the big bug, the failure to parse is fixed, but the timeouts will be ignored now, correct? A good step forward, but being able to set socket timeouts will help a lot when dealing with outages and network issues. Without the ability to set timeouts we're just asking for a bad socket to hang either a request or the entire connection pool depending on the circumstances.

**Comment by jodok** [comment]
yes @reversefold, as mentioned by @celaus we decided to release a quick fix now. we are still working on the full implementation.

**Comment by reversefold** [comment]
Just confirming, thanks.
