### ISSUE TITLE
Major memory/connection leak

### ISSUE THREAD

**Issue by reversefold** [crate/crate-jdbc#82]
We're having major issues with our crate connections growing continuously in our application. We're using (an old version of) DBCP and are not having the same issue with connections to mysql. The number of connections keeps going up far past what the pool is configured for max connections. I'm worried that since crate-jdbc does not appear to actually close the connection when CrateConnection.close() is called the connection object not only is never closed but also stays in memory over time as we are also having issues with our JVMs running out of heap memory.

**Comment by chaudum** [comment]
https://github.com/crate/crate-jdbc/commit/2e64e5eccc58d0612e07d17a105a78bb67b83d4f
