### ISSUE TITLE
CrateConnection's getTransactionIsolation() method is not implemented per JDBC Connection contract

### ISSUE THREAD

**Issue by bin01** [crate/crate-jdbc#88]
Current implementation of CrateConnection#getTransactionIsolation() throws SQLFeatureNotSupportedException as transactions are not supported by the Crate. However, per the java.sql.Connection.getTransactionIsolation() documentation, if Transactions are not supported, the Database Driver needs to return Connection#TRANSACTION_NONE. 

This issue is blocking us from using HikariCP as a connection pool provider.

**Comment by celaus** [comment]
Hi! Thanks for fixing this. I am going to investigate why Travis fails - but until then please sign our CLA: https://crate.io/community/contribute/agreements so we can merge your fix.

Again, Thanks a lot! 

Cheers, Claus

**Comment by bin01** [comment]
Signed the CLA.

**Comment by chaudum** [comment]
@bin01 I've added a changelog entry and updated tests so they pass also with java 7 and merged your changes into master.
I've also done a release already which is available from [Bintray](https://bintray.com/crate/crate/crate-jdbc/view).
